/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tesco.billingsystem.gui;

import com.tesco.billingsystem.bo.EmployeeBO;
import com.tesco.billingsystem.bo.ExcessInventoryException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramsat
 */
public class MainMenu extends javax.swing.JFrame {

    private EmployeeVO empVO;

    public MainMenu() {
        initComponents();
    }

    public MainMenu(EmployeeVO empVO) {
        //
        initComponents();
        welcome_txt.setText(empVO.getName());
        this.empVO = empVO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        welcome_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        delete_txt = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ic_update_txt = new javax.swing.JTextField();
        name_update_txt = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        create_icno_txt = new javax.swing.JTextField();
        create_pwd_txt = new javax.swing.JTextField();
        create_name_txt = new javax.swing.JTextField();
        create_btn = new javax.swing.JButton();
        list_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome");

        jLabel2.setText("ICNO");

        delete_btn.setText("REMOVE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jLabel3.setText("ICNO");

        jLabel4.setText("NAME");

        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel5.setText("ICNO");

        jLabel6.setText("PWD");

        jLabel7.setText("NAME");

        create_btn.setText("CREATE");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });

        list_btn.setText("LIST");
        list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_btnActionPerformed(evt);
            }
        });

        list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ICNO", "PWD", "NAME"
            }
        ));
        jScrollPane2.setViewportView(list_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcome_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(delete_txt)
                            .addComponent(ic_update_txt)
                            .addComponent(name_update_txt)
                            .addComponent(create_icno_txt)
                            .addComponent(create_pwd_txt)
                            .addComponent(create_name_txt))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delete_btn)
                            .addComponent(update_btn)
                            .addComponent(create_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(list_btn)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(welcome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(delete_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ic_update_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name_update_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(create_icno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(create_pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(create_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_btn))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(list_btn)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        //EmployeeVO empVO = new EmployeeVO();
        empVO.setIcno(delete_txt.getText());
        EmployeeBO empBO = new EmployeeBO();
        empBO.deleteEmployee(empVO);
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        //EmployeeVO empVO = new EmployeeVO();
        empVO.setIcno(ic_update_txt.getText());
        empVO.setName(name_update_txt.getText());
        EmployeeBO empBO = new EmployeeBO();
        empBO.updateEmployeeName(empVO);
    }//GEN-LAST:event_update_btnActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        //EmployeeVO empVO = new EmployeeVO();

        EmployeeBO empBO = new EmployeeBO();
        ArrayList<EmployeeVO> list = new ArrayList<EmployeeVO>();
        //list = empBO.displayAllEmployee(empVO);
        
       
            try {
                empBO.validate(list.size());
                
            } catch (ExcessInventoryException ex) {
                JOptionPane.showMessageDialog(rootPane, "Have reached the limit of user");
            }
       
            empVO.setIcno(create_icno_txt.getText());
            empVO.setPwd(create_pwd_txt.getText());
            empVO.setName(create_name_txt.getText());
            empBO.createNewEmployee(empVO);
        
    }//GEN-LAST:event_create_btnActionPerformed

    private void list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_btnActionPerformed

        EmployeeBO empBO = new EmployeeBO();
        ArrayList<EmployeeVO> list = new ArrayList<EmployeeVO>();
        empBO.displayAllEmployee(empVO); //object containing list
        
        //System.out.println(empVO.getList());
        list = empVO.getList();
        for (int i = 0; i < list.size(); i++) {

            DefaultTableModel model = (DefaultTableModel) list_table.getModel();
            model.addRow(new Object[]{list.get(i).getIcno(), list.get(i).getPwd(), list.get(i).getName()});
        }


    }//GEN-LAST:event_list_btnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_btn;
    private javax.swing.JTextField create_icno_txt;
    private javax.swing.JTextField create_name_txt;
    private javax.swing.JTextField create_pwd_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField delete_txt;
    private javax.swing.JTextField ic_update_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton list_btn;
    private javax.swing.JTable list_table;
    private javax.swing.JTextField name_update_txt;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField welcome_txt;
    // End of variables declaration//GEN-END:variables
}
